# This workflow will install Astral UV and attempt to build the package against multiple python versions
name: Test Build using UV

on:
  push:
    branches: [ "main", "develop", "manual" ]
  pull_request:
    branches: [ "main", "develop", "manual" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Build using UV
        run: uv build
